export EVENTUATE_COMMON_VERSION=0.16.0.RELEASE
export EVENTUATE_JAVA_BASE_IMAGE_VERSION=BUILD-16
export EVENTUATE_MESSAGING_KAFKA_IMAGE_VERSION=0.16.0.RELEASE
export EVENTUATE_CDC_VERSION=0.14.0.RELEASE
export EVENTUATE_CDC_PROFILES=EventuatePolling
export EVENTUATE_SAGA_VERSION=0.20.0.RELEASE

